import Head from 'next/head'
import { Center, Card, Text } from '@chakra-ui/react'
import AddTodo from '@/components/AddTodo'
import Todos from '@/components/Todos'
import React from 'react'
import { dehydrate, QueryClient, useQuery } from '@tanstack/react-query'
import axios from 'axios'
import { PostsInterface } from '@/interfaces/PostsInterface'

interface IFormInput {
  title: string;
  descriptions: string;

}

const fetchPosts = async () => {
  const { data } = await axios.get('https://jsonplaceholder.typicode.com/posts');
  return data;
};

export default function Home() {
  const { data } = useQuery({ queryKey: ['posts'], queryFn: fetchPosts })

  const newData = data?.slice(0, 3)

  const [todos, setTodos] = React.useState(newData)


  const _onSubmit = (v: IFormInput) => {
    const initialData = [...todos]
    const value: PostsInterface = {
      title: v.title,
      body: v.descriptions,
      id: 2,
      userId: 1671
    }
    initialData.push(value)
    setTodos(initialData)

  }

  return (
    <>
      <Head>
        <title>Tes Front End Developer PT Informatika Media Pratama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Center h='100vh' color='white' sx={{ backgroundImage: '#fff' }}>
        <Card p={8} w={[350, 450, 600]} >
          <Text fontSize='2xl' color='#000' textAlign='start' fontWeight='700'>Todo App</Text>
          <Todos data={todos} />
          <AddTodo onSubmitForm={(v) => _onSubmit(v)} />
        </Card>
      </Center>
    </>
  )
}
export async function getStaticProps() {
  const queryClient = new QueryClient()

  await queryClient.prefetchQuery(['posts'], fetchPosts)

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  }
}
